name:                to-lecture
version:             0.1.0.0
github:              "githubuser/to-lecture"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/to-lecture#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  to-lecture-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - to-lecture

tests:
  to-lecture-tests:
    build-tools: hspec-discover
    main: TestMain.hs
    source-dirs:
    - test
    dependencies:
    - to-lecture
    - hspec
    - QuickCheck
